"""Fixed dimensions and decoder settings for the pinned Basic Pitch model."""

from __future__ import annotations

import numpy as np

MODEL_ID = "spotify-basic-pitch-icassp-2022-v0.4.0"
SPOTIFY_REPOSITORY = "spotify/basic-pitch"
SPOTIFY_REVISION = "9991303bba609a3b93089d13ec80d1d495083596"
SPOTIFY_ONNX_PATH = "basic_pitch/saved_models/icassp_2022/nmp.onnx"
SPOTIFY_ONNX_GIT_BLOB_SHA1 = "c30e5f9438e798604b7177aa26be1fe64482f767"
SPOTIFY_ONNX_SIZE_BYTES = 230_444
ONNX_INPUT_NAME = "serving_default_input_2:0"
ONNX_OUTPUT_NOTE = "StatefulPartitionedCall:1"
ONNX_OUTPUT_ONSET = "StatefulPartitionedCall:2"
ONNX_OUTPUT_CONTOUR = "StatefulPartitionedCall:0"

AUDIO_SAMPLE_RATE = 22_050
AUDIO_N_CHANNELS = 1
FFT_HOP = 256
AUDIO_WINDOW_SECONDS = 2
AUDIO_N_SAMPLES = AUDIO_SAMPLE_RATE * AUDIO_WINDOW_SECONDS - FFT_HOP
ANNOTATIONS_FPS = AUDIO_SAMPLE_RATE // FFT_HOP
ANNOT_N_FRAMES = ANNOTATIONS_FPS * AUDIO_WINDOW_SECONDS

ANNOTATIONS_BASE_FREQUENCY = 27.5
ANNOTATIONS_N_SEMITONES = 88
NOTES_BINS_PER_SEMITONE = 1
CONTOURS_BINS_PER_SEMITONE = 3
N_FREQ_BINS_NOTES = ANNOTATIONS_N_SEMITONES * NOTES_BINS_PER_SEMITONE
N_FREQ_BINS_CONTOURS = ANNOTATIONS_N_SEMITONES * CONTOURS_BINS_PER_SEMITONE

CQT_N_BINS = N_FREQ_BINS_CONTOURS + 45
CQT_N_FILTERS = 36
CQT_KERNEL_LENGTH = 256
CQT_TOP_HOP = FFT_HOP
CQT_INPUT_REFLECTION = 128
DOWNSAMPLE_FILTER_LENGTH = 256
DOWNSAMPLE_REFLECTION = (DOWNSAMPLE_FILTER_LENGTH - 1) // 2
FRONTEND_BATCHNORM_EPS = 1e-3

HARMONIC_SHIFTS = (-36, 0, 36, 57, 72, 84, 93, 101)
HARMONIC_OUTPUT_BINS = N_FREQ_BINS_CONTOURS

ONSET_THRESHOLD = 0.5
FRAME_THRESHOLD = 0.3
MIN_NOTE_LENGTH_MS = 127.7
MIN_NOTE_LENGTH_FRAMES = 11
OVERLAP = 30

FREQ_BINS_NOTES = ANNOTATIONS_BASE_FREQUENCY * 2.0 ** (
    np.arange(N_FREQ_BINS_NOTES, dtype=np.float64) / 12.0
)
FREQ_BINS_CONTOURS = ANNOTATIONS_BASE_FREQUENCY * 2.0 ** (
    np.arange(N_FREQ_BINS_CONTOURS, dtype=np.float64)
    / (12.0 * CONTOURS_BINS_PER_SEMITONE)
)
